package org.superside.constants.generator

import org.superside.constants.extension.UnleashExtension
import org.superside.constants.model.Feature
import java.io.File

abstract class FeatureGenerator {

    abstract fun generate(
        features: List<Feature>,
        unleashExtension: UnleashExtension,
        generatedSrcDir: File
    )

    companion object {
        const val FILE_HEADER_KDOC = "This class is generated by the Unleash Codegen Gradle plugin. Do not edit."
    }
}
