package com.superside.unleash.codegen.generator

import com.superside.unleash.codegen.extension.UnleashExtension
import com.superside.unleash.codegen.model.Feature
import java.io.File

abstract class FeatureGenerator {
    abstract fun generate(
        features: List<Feature>,
        unleashExtension: UnleashExtension,
        projectDirectory: File,
    )

    companion object {
        const val FILE_HEADER_KDOC =
            "CLASS IS GENERATED BY THE UNLEASH CODEGEN GRADLE PLUGIN. DO NOT EDIT."
    }
}
