package io.github.ybarkouski.unleash.codegen.generator

import io.github.ybarkouski.unleash.codegen.extension.UnleashExtension
import io.github.ybarkouski.unleash.codegen.model.Feature
import java.io.File

abstract class FeatureGenerator {

    abstract fun generate(
        features: List<Feature>,
        unleashExtension: UnleashExtension,
        projectDirectory: File
    )

    companion object {
        const val FILE_HEADER_KDOC =
            "CLASS IS GENERATED BY THE UNLEASH CODEGEN GRADLE PLUGIN. DO NOT EDIT."
    }
}
