package org.superside.unleash.codegen.generator

import org.superside.unleash.codegen.model.Feature
import java.io.File

abstract class FeatureGenerator {

    abstract fun generate(
        features: List<Feature>,
        packageName: String,
        projectName: String,
        projectDirectory: File
    )

    companion object {
        const val FILE_HEADER_KDOC =
            "CLASS IS GENERATED BY THE UNLEASH CODEGEN GRADLE PLUGIN. DO NOT EDIT."
    }
}
